###服务端口号
server:
  port: 8001
spring:
  application:
    name: black-shop-basic-apollo
###nacos 基本信息配置
  cloud: 
    nacos: 
      discovery: 
        server-addr: 192.168.0.238:8848
apollo: 
  meta:  http://192.168.0.238:8080
   