version: "3.3"  
services:
  blackshop-mysql:
    container_name: mysql
    image: mysql:8.0.18
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${GLOBAL_TIME_ZONE}
    ports:
      - "${MYSQL_PORT}:3306"
  blackshop-redis:
    image: redis:5.0.8
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data

networks:
  bs-backend:  
    driver: bridge
